### ISSUE TITLE
different toolchains

### ISSUE THREAD

**Issue by dakyskye** [Sreyas-Sreelal/rs-plugin-boilerplate#2]
You say we need to install *nightly* compiler [here](https://github.com/Sreyas-Sreelal/rs-plugin-boilerplate#setup-compiler) while you provide *stable* compiler in makefile. [here](https://github.com/Sreyas-Sreelal/rs-plugin-boilerplate/blob/f1b1f0432486ad285e2ea73b32f47c1243a133f9/makefile#L2) & [here](https://github.com/Sreyas-Sreelal/rs-plugin-boilerplate/blob/f1b1f0432486ad285e2ea73b32f47c1243a133f9/makefile#L9).

**Comment by Sreyas-Sreelal** [comment]
Thanks for pointing it out, changed it now :)

**Comment by dakyskye** [comment]
Glad to hear.
